create sequence seq_mvcboard_num
    increment by 1
    start with 1
    minvalue 1
    nomaxvalue
    nocycle
    nocache;
    
create sequence seq_acmboard_num
    increment by 1
    start with 1
    minvalue 1
    nomaxvalue
    nocycle
    nocache;
    
create sequence seq_cmboard_num
    increment by 1
    start with 1
    minvalue 1
    nomaxvalue
    nocycle
    nocache;

create sequence seq_community_num
    increment by 1
    start with 1
    minvalue 1
    nomaxvalue
    nocycle
    nocache;
--------------------------------------------------------------------------------------
CREATE TABLE ACMBOARD 
(
  IDX NUMBER NOT NULL 
, NAME VARCHAR2(50 BYTE) NOT NULL 
, TITLE VARCHAR2(200 BYTE) NOT NULL 
, CONTENT VARCHAR2(2000 BYTE) NOT NULL 
, POSTDATE DATE DEFAULT sysdate NOT NULL 
, OFILE VARCHAR2(200 BYTE) 
, SFILE VARCHAR2(30 BYTE) 
, DOWNCOUNT NUMBER(5, 0) DEFAULT 0 NOT NULL 
, VISITCOUNT NUMBER DEFAULT 0 NOT NULL 
, CONSTRAINT SYS_C008644 PRIMARY KEY 
  (
    IDX 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX SYS_C008644 ON ACMBOARD (IDX ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;
--------------------------------------------------------------------------------------
CREATE TABLE CMBOARD 
(
  IDX NUMBER NOT NULL 
, BOARD_IDX NUMBER NOT NULL 
, REPLY VARCHAR2(50 BYTE) NOT NULL 
, WRITER VARCHAR2(50 BYTE) NOT NULL 
, REPLY_DATE DATE DEFAULT sysdate NOT NULL 
, REPLY_CONTENT VARCHAR2(2000 BYTE) NOT NULL 
, CONSTRAINT SYS_C008658 PRIMARY KEY 
  (
    IDX 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX SYS_C008658 ON CMBOARD (IDX ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;
--------------------------------------------------------------------------------------
CREATE TABLE COMMUNITY 
(
  IDX NUMBER NOT NULL 
, NAME VARCHAR2(50 BYTE) NOT NULL 
, TITLE VARCHAR2(200 BYTE) NOT NULL 
, CONTENT VARCHAR2(2000 BYTE) NOT NULL 
, POSTDATE DATE DEFAULT sysdate NOT NULL 
, OFILE VARCHAR2(200 BYTE) 
, SFILE VARCHAR2(30 BYTE) 
, DOWNCOUNT NUMBER(5, 0) DEFAULT 0 NOT NULL 
, VISITCOUNT NUMBER DEFAULT 0 NOT NULL 
, CONSTRAINT SYS_C008651 PRIMARY KEY 
  (
    IDX 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX SYS_C008651 ON COMMUNITY (IDX ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;
--------------------------------------------------------------------------------------
CREATE TABLE MEMBER 
(
  ID VARCHAR2(100 BYTE) NOT NULL 
, NAME VARCHAR2(100 BYTE) NOT NULL 
, PWD VARCHAR2(100 BYTE) NOT NULL 
, NICKNAME VARCHAR2(100 BYTE) NOT NULL 
, PHONE VARCHAR2(100 BYTE) 
, EMAIL VARCHAR2(200 BYTE) NOT NULL 
, POSTCODE VARCHAR2(100 BYTE) NOT NULL 
, POST VARCHAR2(200 BYTE) NOT NULL 
, BAN VARCHAR2(20 BYTE) NOT NULL 
, CONSTRAINT MEMBER_PK PRIMARY KEY 
  (
    ID 
  , NICKNAME 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX MEMBER_PK ON MEMBER (ID ASC, NICKNAME ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;

COMMENT ON COLUMN MEMBER.ID IS '아이디';

COMMENT ON COLUMN MEMBER.NAME IS '이름';

COMMENT ON COLUMN MEMBER.PWD IS '비밀번호';

COMMENT ON COLUMN MEMBER.NICKNAME IS '별명';

COMMENT ON COLUMN MEMBER.PHONE IS '전화번호';

COMMENT ON COLUMN MEMBER.EMAIL IS '이메일';

COMMENT ON COLUMN MEMBER.POSTCODE IS '우편번호';

COMMENT ON COLUMN MEMBER.POST IS '주소';

COMMENT ON COLUMN MEMBER.BAN IS '정지유무';
--------------------------------------------------------------------------------------
CREATE TABLE MVCBOARD 
(
  IDX NUMBER NOT NULL 
, NAME VARCHAR2(50 BYTE) NOT NULL 
, TITLE VARCHAR2(200 BYTE) NOT NULL 
, CONTENT VARCHAR2(2000 BYTE) NOT NULL 
, POSTDATE DATE DEFAULT sysdate NOT NULL 
, OFILE VARCHAR2(200 BYTE) 
, SFILE VARCHAR2(30 BYTE) 
, DOWNCOUNT NUMBER(5, 0) DEFAULT 0 NOT NULL 
, VISITCOUNT NUMBER DEFAULT 0 NOT NULL 
, CONSTRAINT SYS_C008577 PRIMARY KEY 
  (
    IDX 
  )
  USING INDEX 
  (
      CREATE UNIQUE INDEX SYS_C008577 ON MVCBOARD (IDX ASC) 
      LOGGING 
      TABLESPACE USERS 
      PCTFREE 10 
      INITRANS 2 
      STORAGE 
      ( 
        INITIAL 65536 
        NEXT 1048576 
        MINEXTENTS 1 
        MAXEXTENTS UNLIMITED 
        BUFFER_POOL DEFAULT 
      ) 
      NOPARALLEL 
  )
  ENABLE 
) 
LOGGING 
TABLESPACE USERS 
PCTFREE 10 
INITRANS 1 
STORAGE 
( 
  INITIAL 65536 
  NEXT 1048576 
  MINEXTENTS 1 
  MAXEXTENTS UNLIMITED 
  BUFFER_POOL DEFAULT 
) 
NOCOMPRESS 
NO INMEMORY 
NOPARALLEL;
--------------------------------------------------------------------------------------
commit;

